name: Push docker images to Dockerhub

on:
  push:
    branches: master
    tags:
      - "v*.*.*"

jobs:
  multi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push latest ToPS
        if: ${{ steps.vars.outputs.tag == 'master' }}
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: opentosca/tops:latest

      - name: Build and push version of ToPS
        if: ${{ steps.vars.outputs.tag != 'master' }}
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: opentosca/tops:${{ steps.vars.outputs.tag }}
